apiVersion: v1
kind: Pod
metadata: 
  name: microservice-libreria-pod
  labels: 
    app: microservice-libreria
    type: microservice
spec: 
  containers:
    - name: microservice-libreria-app
      image: 1152715676/serviciosapilibreria:latest
      ports: 
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://juan_gonzalez:$JuanGonzalez9930@mongo-service:27017
