apiVersion: v1
kind: Pod
metadata: 
  name: mongo-pod
  labels: 
    app: microservice-libreria
    name: mongo-pod
spec: 
  containers:
    - name: mongo
      image: mongo:4.4.12
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "juan_gonzalez"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$JuanGonzalez9930"
      ports: 
        - containerPort: 27017